#!/bin/bash
set -euo pipefail

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [[ $# -lt 1 ]]; then
    echo "Usage: brew gomod github.com/foo/bar@version"
    exit 1
fi

MODULE_PATH="${1%@*}"
NAME="${MODULE_PATH//[\/\.]/-}"
VERSION="${1##*@}"
if [ -z "${VERSION}" ] || [ "${VERSION}" = "latest" ] || [ "${VERSION}" = "${MODULE_PATH}" ]; then
    VERSION="latest"
    BREW_VERSION="0.$(date '+%Y%m%d.%H%M%S')"
else
    BREW_VERSION="${VERSION}"
fi

brew list "gomod-${NAME}" >/dev/null 2>&1 && \
    brew uninstall "gomod-${NAME}"

ROOT="$(brew --prefix)/Cellar/gomod-${NAME}/${BREW_VERSION}"
mkdir -p "$ROOT"
cd "$ROOT"
export GOBIN="$ROOT/bin"
go install "${MODULE_PATH}@${VERSION}"

brew link "gomod-${NAME}"
